name: ExcellentJobs
main: su.nightexpress.excellentjobs.JobsPlugin
version: '${project.version}'
description: A better & elegant jobs solution for your server!
author: NightExpress
depend: [nightcore]
softdepend:
  - MythicMobs
  - PlaceholderAPI
  - CoinsEngine
  - Vault
  - ProtocolLib
api-version: 1.18